account/urls.py
from django.urls import path

from .views import LoginView, RegisterView

app_name = 'account'

urlpatterns = [ 
    path('register', RegisterView.as_view(), name='register_page'),
    path('login',LoginView.as_view(), name='login_page')
]

dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'


urlpatterns = [
    path('', views.index_dashboard, name='dashboard_index'),
    path('add-blog', views.AddBlog.as_view(), name='add_blog'),
    path('logout', views.logout_user, name='logout'),
    path('edit-blog/<int:pk>', views.UpdateBLog.as_view(), name='edit_blog'),
    path('list-blog', views.ListsBlog.as_view(), name='lists_blog'),
    path('delete-blog/<int:pk>', views.DeleteBlog.as_view(), name='delete_blog'),
    path('<int:pk>/update-profile', views.Profile.as_view(), name='profile'),
    path('change-password', views.ChangePassword.as_view(), name='change_password'),
    path('upload-image', views.UploadImage.as_view(), name='upload_image'),
    path('list-images', views.ListImages.as_view(), name='list_images')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.shortcuts import render

def index_page(request):
    return render(request, 'main/index.html')

app_name = 'main'


urlpatterns = [
    path('', index_page, name='index_page'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('blog/', include('posts.urls')),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path, path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path('detail/(?P<slug>[\w\d-]+)$', views.BlogDetail.as_view(), name='detail_blog'),
    re_path('category/(?P<slug>[\w\d-]+)$', views.PostCategories.as_view(), name='category'),
    path('list-categories', views.ListCategories.as_view(), name='list_categories'),
    path('', views.BlogList.as_view(), name='bloglist')
]

django_blog/templates/main/utils/msg.html
{% if messages %}
    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
{% endif %}

django_blog/templates/main/utils/navbar.html
  <nav class="navbar navbar-expand-lg navbar-light m-4">
      <a class="navbar-brand text-danger" href="#" style="font-weight: 400;">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:bloglist' %}">Blog</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
              
                  <a class="dropdown-item" href="{% url 'dashboard:lists_blog' %}">Your Blog</a>
                  <a class="dropdown-item" href="{% url 'dashboard:add_blog' %}">Add blog</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'dashboard:logout' %}">Logout</a>
              </div>
              {% else %}
              <a class='dropdown-item' href='{% url "account:login_page" %}'>Login</a>
              <a class='dropdown-item' href='{% url "account:register_page" %}'>Register</a>
            {% endif %}
          </li>
      </div>
    </nav>