account/urls.py
from django.urls import path

from .views import LoginView, RegisterView

app_name = 'account'

urlpatterns = [ 
    path('register', RegisterView.as_view(), name='register_page'),
    path('login',LoginView.as_view(), name='login_page')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.shortcuts import render

def index_page(request):
    return render(request, 'main/index.html')

app_name = 'main'


urlpatterns = [
    path('', index_page, name='index_page'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('blog/', include('posts.urls')),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path, path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path('detail/(?P<slug>[\w\d-]+)$', views.BlogDetail.as_view(), name='detail_blog'),
    re_path('category/(?P<slug>[\w\d-]+)$', views.PostCategories.as_view(), name='category'),
    path('list-categories', views.ListCategories.as_view(), name='list_categories'),
    path('', views.BlogList.as_view(), name='bloglist')
]

django_blog/templates/main/base.html
<html>
    <head>
        <title>{% block title %} Account {% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>    
        <link href="https://fonts.googleapis.com/css2?family=Dosis&family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet"> 

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% load static %}
        <link rel='stylesheet' href='{% static "main/css/styles.css" %}'>
        {% block additional_static %}  {% endblock %}
    </head>
<body>
    {% block content %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

django_blog/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} Django Web App {% endblock %}

{% block content %}
{% include 'main/utils/navbar.html' %}
{% load post_tags %}
<div class="row d-flex">
    <div class="container">
        <div class="col-lg-6 mt-4 hero">
            <h2 style="font-weight: 300;">Blog Web App with Django</h2>
            <p class='text-opening'>
                    If there's no book beside you, maybe you can read someone's writing here. Or maybe you want to be a contributor to the art of writing here?
            </p>
            <p class="mt-2">
                <a href="{% url 'account:register_page' %}" class="btn btn-outline-dark">Sign Up</a>
                <a href="{% url 'account:login_page' %}" class="btn btn-outline-dark">Sign In</a>
            </p>
            </p>
        </div>
    </div>
</div>
<div class="mt-5 d-flex justify-content-center mb-3">
    <h3 class="justify-content-center">Recent Posts</h3>
</div>
<div class="container">
    <div class="row d-flex">
        {% recent_posts as recent %}

        {% for recents in recent %}
        <div class="col-lg-3 mb-3">
            <div class="card">
                
                <div class="card-body">
                <h5 class="card-title">{{recents.title}}</h5>
                <p class="card-text">{{recents.body_text|short_description:"99"}}...</p>
                <a href="{% url 'blog:detail_blog' recents.slug %}" class="btn btn-dark">Read More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


</div>
{% endblock %}