dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'


urlpatterns = [
    path('', views.index_dashboard, name='dashboard_index'),
    path('add-blog', views.AddBlog.as_view(), name='add_blog'),
    path('logout', views.logout_user, name='logout'),
    path('edit-blog/<int:pk>', views.UpdateBLog.as_view(), name='edit_blog'),
    path('list-blog', views.ListsBlog.as_view(), name='lists_blog'),
    path('delete-blog/<int:pk>', views.DeleteBlog.as_view(), name='delete_blog'),
    path('<int:pk>/update-profile', views.Profile.as_view(), name='profile'),
    path('change-password', views.ChangePassword.as_view(), name='change_password'),
    path('upload-image', views.UploadImage.as_view(), name='upload_image'),
    path('list-images', views.ListImages.as_view(), name='list_images')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.shortcuts import render

def index_page(request):
    return render(request, 'main/index.html')

app_name = 'main'


urlpatterns = [
    path('', index_page, name='index_page'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('blog/', include('posts.urls')),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path, path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path('detail/(?P<slug>[\w\d-]+)$', views.BlogDetail.as_view(), name='detail_blog'),
    re_path('category/(?P<slug>[\w\d-]+)$', views.PostCategories.as_view(), name='category'),
    path('list-categories', views.ListCategories.as_view(), name='list_categories'),
    path('', views.BlogList.as_view(), name='bloglist')
]

dashboard/forms.py
from random import choices
from django.forms import ModelForm
from django import forms 
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from posts.models import Post, Category, Images

from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

class BlogForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit','Add Blog '))
    
    class Meta:
        model = Post 
        fields = ('title','edit_permission','categories','body_text', 'img')
    
    edit_permission = forms.ChoiceField(required=False, 
                                        choices=(
                                            (0,'Anyone can edit'),
                                            (1,'Only admin and you can edit')
                                        )
                    )
    
    categories = forms.ModelMultipleChoiceField(required=False, 
                                        queryset=Category.objects.all(),
                                        widget=forms.CheckboxSelectMultiple)
    
    body_text = forms.Textarea(attrs={'id':'editor1'})
    title = forms.CharField(min_length=20, max_length=60)
    img = forms.ImageField(required=False)

class ProfileForm(ModelForm):

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        for field in self.fields:
            self.fields[field].help_text = False 
        
        self.helper.add_input(Submit('submit', 'Submit'))

    
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
    
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    username = forms.CharField(required=False)

class ChangePasswordCustom(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit','Change'))
        
        for field in self.fields:
            self.fields[field].help_text = False 

class ImageUploads(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit','Add Images'))

    class Meta:
        model = Images    
        fields = ('name', 'img')
    

dashboard/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.decorators import method_decorator

from django.views.generic import (
                                FormView, 
                                UpdateView, 
                                ListView, 
                                DeleteView)
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView

from .forms import BlogForm, ProfileForm, ChangePasswordCustom, ImageUploads
from posts.models import Post, Images
import os 

@login_required(login_url='/account/login')
def index_dashboard(request):
    return render(request, template_name='dashboard/index.html')

@login_required(login_url='/account/login')
def logout_user(request):
    logout(request)
    messages.warning(request, 'Logged out')
    return redirect(reverse('account:login_page'))

class AddBlog(FormView):

    template_name = 'dashboard/add-blog.html'
    form_class = BlogForm

    def get_success_url(self, **kwargs) -> str:
        return reverse('dashboard:edit_blog', kwargs={'pk':kwargs.get('pk')})
    
    def form_valid(self, form):
        result = form.save(commit=False)
        result.author = self.request.user 
        result.save()
        
        messages.success(self.request, 'Blog Added')
        return redirect(self.get_success_url(pk=result.pk))
    
    @method_decorator(login_required(login_url='/account/login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class UpdateBLog(UpdateView):
    model = Post 
    form_class = BlogForm
    template_name = 'dashboard/add-blog.html'

    def get_success_url(self) -> str:
        return reverse('dashboard:edit_blog', args=(self.kwargs.get('pk'),))
    
    @method_decorator(login_required(login_url='/account/login'))
    def dispatch(self, request, *args, **kwargs):
        try:
            result = self.get_object()
            if result.author != request.user and (not request.user.is_superuser and result.edit_permission != 0):
                return redirect(reverse('dashboard:add_blog'))
        except Exception as e:
            print(e)
            return redirect(reverse('dashboard:add_blog'))
        return super().dispatch(request, *args, **kwargs)

class ListsBlog(ListView):
    model = Post 
    template_name = 'dashboard/lists-blog.html'
    context_object_name = 'blog_lists'
    paginate_by = 7

    @method_decorator(login_required(login_url='/account/login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        if self.request.user.is_superuser:
            result = self.model.objects.all()
        else:
            result = self.model.objects.filter(
                    Q(author=self.request.user) | Q(edit_permission=0)
            )
        return result

class DeleteBlog(DeleteView):
    model = Post 
    template_name = 'dashboard/delete-blog.html'

    def get_success_url(self) -> str:
        return reverse('dashboard:lists_blog')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.model.objects.get(pk=self.kwargs.get('pk')).title
        return context
    
    def form_valid(self, form):
        self.object = self.get_object()
        if os.path.exists(self.object.img.path):
            os.remove(self.object.img.path)
        self.object.delete()
        return redirect(self.get_success_url())

class Profile(UpdateView):
    template_name = 'dashboard/profile.html'
    model = User 
    form_class = ProfileForm

    def get_success_url(self) -> str:
        return reverse('dashboard:profile', kwargs={'pk':self.request.user.pk})
    
    def dispatch(self, request, *args, **kwargs):
        """
        validating, if user visit another edit profile page user, 
        it will be redirecting to user edit profile page 
        """
        if request.user.pk != self.kwargs.get('pk') and not request.user.is_superuser:
            return redirect(reverse('dashboard:profile', kwargs={'pk':request.user.pk}))
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        messages.success(self.request, 'Profile Edited!')
        return super().form_valid(form)

class ChangePassword(PasswordChangeView):
    form_class = ChangePasswordCustom
    template_name = 'dashboard/change-password.html'

    def get_success_url(self) -> str:
        return reverse('dashboard:change_password')
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            update_session_auth_hash(request, request.user)
        return super().post(request, *args, **kwargs)

class UploadImage(FormView):
    model = Images
    form_class = ImageUploads
    template_name = 'dashboard/upload-images.html'
    
    def get_success_url(self) -> str:
        return reverse('dashboard:list_images')
    
    def form_valid(self, form):
        ins = form.save(commit=False)
        ins.author = self.request.user 
        ins.save()
        
        return super().form_valid(form)

class ListImages(ListView):
    model = Images
    context_object_name = 'images'
    
    template_name = 'dashboard/list-images.html'

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)
    

dashboard/templates/dashboard/add-blog.html
{% include 'dashboard/index.html' %}
{% load crispy_forms_tags %}

<div class='container'>
    {% include 'main/utils/msg.html' %}
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
<script>
   CKEDITOR.replace('id_body_text', {
                    filebrowserBrowseUrl: '/dashboard/list-images',
                })
                
                CKEDITOR.on('instanceReady', function(evt) {
                    evt.editor.dataProcessor.htmlFilter.addRules({
                        elements: {
                            img: function(el){
                                el.addClass('img-fluid'),
                                el.addClass('mb-5'),
                                el.addClass('rounded')
                            }
                        }
                    })
                })
</script>

dashboard/templates/dashboard/change-password.html
{% include 'dashboard/index.html' %}
{% load crispy_forms_tags %}

<div class='container'>
    {% include 'main/utils/msg.html' %}
    <form method='POST'>
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>

dashboard/templates/dashboard/delete-blog.html
{% include 'dashboard/index.html' %}

<div class='container'>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure want to delete this "{{title}}"?</p>
        <button type='submit' class='btn btn-outline-danger'>Delete</submit>
    </form>
</div>

dashboard/templates/dashboard/index.html
{% extends 'main/base.html' %}



{% block title %} Welcome to the play-zone!{% endblock %}
{% block additional_static %}

{% load static %}
<link rel='stylesheet' href='{% static "dashboard/css/styles.css"%}'>

{% endblock %}
{% block content %}

{% include 'dashboard/utils/sidebar.html' %}

<button class="openbtn" onclick="openNav()" style='margin-left: 20px;margin-top: 15px;'>☰</button>  
<script type='text/javascript' src='{% static "dashboard/js/script.js"%}'></script>
<script src='https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js'></script>
{% endblock %}

dashboard/templates/dashboard/list-images.html
{% include 'dashboard/index.html' %}

<div class="container">
    <div class="row">
        {% for img in images %}
            <img src="{{img.img.url}}" class="img-thumbnail w-50" alt="{{img.name}}" onclick="clickimage(this)">
        {% endfor %}
    </div>

</div>
<script type='text/javascript'>
function getUrlParam( paramName ) {
        var reParam = new RegExp( '(?:[\?&]|&)' + paramName + '=([^&]+)', 'i' );
        var match = window.location.search.match( reParam );

        return ( match && match.length > 1 ) ? match[1] : null;
        }
function clickimage(img){
        var funcNum = getUrlParam('CKEditorFuncNum')
        window.opener.CKEDITOR.tools.callFunction(funcNum, img.src);
        window.close()
}
</script>

dashboard/templates/dashboard/lists-blog.html
{% include 'dashboard/index.html' %}

{% load my_filter %}

<div class='container mt-2'>
    <div class='table-responsive-sm'>
        <table class='table table-bordered'>
            <thead>
                <tr>
                    <th scope='col'>ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for blog in blog_lists %}
                <tr>
                    <th scope='row'>{{blog.id}}</th>
                    <td>{{blog.title}}</td>
                    <td>
                        <a href='{% url "dashboard:edit_blog" blog.id %}' class='mr-1'>Edit</a>
                        <a href='{% url "dashboard:delete_blog" blog.id %}' class='text-danger'>Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if is_paginated %}
            <div class='d-flex justify-content-center'>
                {% for i in page_obj.paginator.num_pages|ro %}
                    <a href='?page={{i}}' class='paginate-link'>{{i}}</a>
                {% endfor %}
        {% endif %}
        </a>
    </div>
</div>

dashboard/templates/dashboard/profile.html
{% include 'dashboard/index.html' %}
{% load crispy_forms_tags %}
<div class='container mt-5'>
    {% include 'main/utils/msg.html' %}
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>

dashboard/templates/dashboard/upload-images.html
{% include 'dashboard/index.html' %}
{% load crispy_forms_tags %}
<div class="container w-50">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>