django_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.shortcuts import render

def index_page(request):
    return render(request, 'main/index.html')

app_name = 'main'


urlpatterns = [
    path('', index_page, name='index_page'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('blog/', include('posts.urls')),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path, path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path('detail/(?P<slug>[\w\d-]+)$', views.BlogDetail.as_view(), name='detail_blog'),
    re_path('category/(?P<slug>[\w\d-]+)$', views.PostCategories.as_view(), name='category'),
    path('list-categories', views.ListCategories.as_view(), name='list_categories'),
    path('', views.BlogList.as_view(), name='bloglist')
]

posts/models.py
from random import choice
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

import os


CHARS = 'abcdefghijklmnopqrstuvwxyz0123456789'

PERMISSION_CHOICES = (
    (0, 'Anyone can edit '),
    (1, 'Only you and admin can edit')
)


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Post(models.Model):


    created_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body_text = models.TextField()
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, default='', editable=False)
    img = models.ImageField(upload_to='images')
    
    edit_permission = models.IntegerField(choices=PERMISSION_CHOICES, default=1)

    categories = models.ManyToManyField(Category, default='uncategorized')

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        
        title = self.title + '-' + ''.join(choice(CHARS) for _ in range(5))
        self.slug = slugify(title, allow_unicode=False)
        super().save(*args, **kwargs)
    
    class Meta:
        ordering = ('created_at',)
    
    

class Images(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images')
    name = models.CharField(default='Undefined', max_length=40)

    def __str__(self):
        return self.name

posts/views.py
from re import template
from django.views.generic import DetailView, ListView
from .models import Post, Category

class BlogDetail(DetailView):
    model = Post 
    context_object_name = 'post'
    template_name = 'posts/show-blog.html'

class BlogList(ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts'
    model = Post 

class PostCategories(ListView):
    """
    Show Posts by Category
    """
    template_name = 'posts/index.html'
    context_object_name = 'posts'
    model = Post 
    
    def get_queryset(self):
        return self.model.objects.filter(categories__name=self.kwargs.get('slug').title()).all()

class ListCategories(ListView):
    template_name = 'posts/list-categories.html'
    model = Category
    context_object_name = 'categories'

    def get_queryset(self):
        return self.model.objects.all().order_by('-name').reverse()

posts/templates/posts/index.html
{% extends 'main/base.html' %}

{% block title %}
    Blog Lists
{% endblock %}

{% load post_tags %}

{% block content %}
{% include 'main/utils/navbar.html' %}
    <div class="container mt-5 body-blog">
       <div class="row">
           <div class="col-lg-8 hero">
               {% for post in posts %}
               <article>
                   <header class="mb-4">
                       <a href="{% url 'blog:detail_blog' post.slug %}"><h3 class="title-blog text-dark">{{post.title}}</h3> </a>
                       <div class="text-muted mb-3 fst-italic">Posted on {{post.created_at}} By {{post.author}}</div>
                   </header>
                   <section class="mb-5">
                       {{post.body_text|short_description}}
                   </section>
               </article>
               {% endfor %}
           </div>
           <div class="col-lg-4">
               {% include 'posts/utils/categories-card.html' %}
           </div>
       </div>
    </div>
{% endblock %}

posts/templates/posts/list-categories.html
{% extends 'main/base.html' %}

{% block title %}
    List Categories
{% endblock %}

{% load post_tags %}

{% block content %}
    {% include 'main/utils/navbar.html' %}
    <div class="container mt-5 body-blog">
        <div class="row hero">
            {% for category in categories %}
            <div class="col-lg-5 mt-2 mb-2 mr-2">
                
                    <a href="{% url 'blog:category' category.name %}" class="text-dark">{{category}}</a>

            </div>
            {% endfor %}
            

        </div>
    </div>
{% endblock %}

posts/templates/posts/show-blog.html
{% extends 'main/base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}
{% block content %}
{% include 'main/utils/navbar.html' %}

{% load post_tags %}

<div class="container mt-5 body-blog">
    <div class="row">
        <div class="col-lg-8 hero">
            <article>
                <header class="mb-4">
                    <h1 class="title-blog">{{post.title}}</h1>
                    <div class="text-muted mb-3 fst-italic">Posted on {{post.created_at}} by {{post.author}}</div>
                    {% if post.categories.all %}
                        {% for categories in post.categories.all %}
                            <a class="btn btn-outline-dark">{{categories}}</a>
                        {% endfor %}
                    {% endif %}
                    {% if post.img|is_exists %}
                        <img src="{{post.img.url}}" class="img-fluid rounded mt-3">
                    {% endif %}
                </header>
                <section class="mb-4 content-blog">
                    {{post.body_text|safe}}
                </section>
            </article>
        </div>
        <div class="col-lg-4 recent-posts">
            <div class="card mb-4">
                <div class="card-header">
                    Recent Posts
                </div>
                <div class="card-body">
                    <ul class="list-unstyled">

                        {% recent_posts as recent %}

                        {% for new_post in recent %}
                            <li>
                                <a href="{% url 'blog:detail_blog' new_post.slug %}" class="text-dark">{{new_post}}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% include 'posts/utils/categories-card.html' %}
        </div>
</div>
{% endblock %}